insert into all_courses(abbr_, name_) values('KAZ 212', 'Academic Kazakh');
insert into all_courses(abbr_, name_) values('WLL 222', 'Acting: Praxis, Theory and History');
insert into all_courses(abbr_, name_) values('MATH 423', 'Actuarial Mathematics');
insert into all_courses(abbr_, name_) values('SHSS 250', 'Advanced Rhetoric and Composition');
insert into all_courses(abbr_, name_) values('PLS 441', 'Advanced Topics in Comparative Politics');
insert into all_courses(abbr_, name_) values('ANT 306', 'Anthropology of Performance');
insert into all_courses(abbr_, name_) values('ANT 302/REL 301', 'Anthropology of Religion and Secularism');
insert into all_courses(abbr_, name_) values('CHEM 451', 'Applied Homogenous Catalysis');
insert into all_courses(abbr_, name_) values('PHYS 271', 'Applied Methods of Computational Physics with Laboratory');
insert into all_courses(abbr_, name_) values('MATH 310', 'Applied Statistical Methods');
insert into all_courses(abbr_, name_) values('ANT 222/SOC 222', 'Approaches to Global Development');
insert into all_courses(abbr_, name_) values('ANT 232', 'Archaeology of Central Asia');
insert into all_courses(abbr_, name_) values('KAZ 101', 'Basic Kazakh I');
insert into all_courses(abbr_, name_) values('KAZ 105', 'Basic Kazakh II');
insert into all_courses(abbr_, name_) values('FRE 102', 'Beginning French II');
insert into all_courses(abbr_, name_) values('GER 101', 'Beginning German');
insert into all_courses(abbr_, name_) values('GER 102', 'Beginning German II');
insert into all_courses(abbr_, name_) values('CHN 102', 'Beginning Mandarin II');
insert into all_courses(abbr_, name_) values('SPA 102', 'Beginning Spanish II');
insert into all_courses(abbr_, name_) values('ECON 405', 'Behavioral and Experimental Economics');
insert into all_courses(abbr_, name_) values('CHEM 341', 'Biochemistry I');
insert into all_courses(abbr_, name_) values('BIOL 341', 'Biochemistry I');
insert into all_courses(abbr_, name_) values('CHEM 341L', 'Biochemistry I Lab');
insert into all_courses(abbr_, name_) values('BIOL 420', 'Bioethics');
insert into all_courses(abbr_, name_) values('BIOL 399', 'Biology Internship - 2B');
insert into all_courses(abbr_, name_) values('BIOL 101', 'Biology for non-Science majors');
insert into all_courses(abbr_, name_) values('REL 212', 'Buddhist Religious Traditions');
insert into all_courses(abbr_, name_) values('KAZ 263', 'Business Etiquette');
insert into all_courses(abbr_, name_) values('MATH 161', 'Calculus I');
insert into all_courses(abbr_, name_) values('MATH 162', 'Calculus II');
insert into all_courses(abbr_, name_) values('MATH 263', 'Calculus III');
insert into all_courses(abbr_, name_) values('MATH 499', 'Capstone Project');
insert into all_courses(abbr_, name_) values('SOC 499', 'Capstone Seminar');
insert into all_courses(abbr_, name_) values('ANT 499', 'Capstone Seminar');
insert into all_courses(abbr_, name_) values('CHEM 400', 'Chemistry Seminar');
insert into all_courses(abbr_, name_) values('CHEM 090', 'Chemistry for Non-Science majors');
insert into all_courses(abbr_, name_) values('PLS 365/SOC 365', 'Civil-Military Relations');
insert into all_courses(abbr_, name_) values('PHYS 362', 'Classical Electrodynamics II');
insert into all_courses(abbr_, name_) values('PHYS 222', 'Classical Mechanics II');
insert into all_courses(abbr_, name_) values('COMM 102', 'Communication Foundations II');
insert into all_courses(abbr_, name_) values('PLS 447', 'Comparative Political Parties');
insert into all_courses(abbr_, name_) values('PLS 371', 'Comparative Welfare States');
insert into all_courses(abbr_, name_) values('PHYS 270', 'Computational Physics');
insert into all_courses(abbr_, name_) values('CSCI 233', 'Computer Networks');
insert into all_courses(abbr_, name_) values('CSCI 307', 'Computer Science Seminar');
insert into all_courses(abbr_, name_) values('KAZ 371', 'Contemporary Kazakh Literature');
insert into all_courses(abbr_, name_) values('WLL 442', 'Contemporary Russian and Russophone Literature');
insert into all_courses(abbr_, name_) values('WLL 352/SPA 352', 'Contemporary Spanish Literature and Cinema: from the transition to the recent economic crisis');
insert into all_courses(abbr_, name_) values('KAZ 362', 'Creative Writing in Kazakh Language');
insert into all_courses(abbr_, name_) values('MATH 417', 'Cryptography');
insert into all_courses(abbr_, name_) values('MATH 441', 'Design of Experiments');
insert into all_courses(abbr_, name_) values('ANT 475', 'Digital Ethnographies');
insert into all_courses(abbr_, name_) values('CSCI 398', 'Directed Study');
insert into all_courses(abbr_, name_) values('PHYS 491', 'Directed Study of Advanced Physics Topics');
insert into all_courses(abbr_, name_) values('MATH 251', 'Discrete Mathematics');
insert into all_courses(abbr_, name_) values('ECON 413', 'Econometrics II');
insert into all_courses(abbr_, name_) values('ECON 211', 'Economic Statistics');
insert into all_courses(abbr_, name_) values('SOC 317', 'Economy and Society');
insert into all_courses(abbr_, name_) values('ROBT 204', 'Electrical and Electronic Circuits II with Lab');
insert into all_courses(abbr_, name_) values('ROBT 304', 'Electromechanical Systems with lab');
insert into all_courses(abbr_, name_) values('SOC 225', 'Environment and Society');
insert into all_courses(abbr_, name_) values('CHEM 471', 'Environmental Chemistry');
insert into all_courses(abbr_, name_) values('PHIL 210', 'Ethics');
insert into all_courses(abbr_, name_) values('HST 132', 'European History II (from 1700)');
insert into all_courses(abbr_, name_) values('PLS 180', 'European Union');
insert into all_courses(abbr_, name_) values('PLS 416', 'Experimental Political Science');
insert into all_courses(abbr_, name_) values('WLL 257', 'Fan Culture in the Age of Convergence');
insert into all_courses(abbr_, name_) values('PLS 360', 'Foreign Policy Analysis');
insert into all_courses(abbr_, name_) values('PHIL 240', 'Formal Logic');
insert into all_courses(abbr_, name_) values('MATH 482', 'Fourier Analysis');
insert into all_courses(abbr_, name_) values('ANT 231', 'Frauds and Fallacies in Archaeology');
insert into all_courses(abbr_, name_) values('ECON 302', 'Game Theory and Economic Analysis');
insert into all_courses(abbr_, name_) values('ANT 480/SOC 418', 'Gender, Power and Social Change in South Asia');
insert into all_courses(abbr_, name_) values('CHEM 101', 'General Chemistry I');
insert into all_courses(abbr_, name_) values('CHEM 102', 'General Chemistry II');
insert into all_courses(abbr_, name_) values('CHEM 102L', 'General Chemistry II lab');
insert into all_courses(abbr_, name_) values('BIOL 370', 'Genetics');
insert into all_courses(abbr_, name_) values('SOC 115', 'Global Social Problems');
insert into all_courses(abbr_, name_) values('PHYS 499', 'Graduation Project');
insert into all_courses(abbr_, name_) values('ROBT 491', 'Graduation Project');
insert into all_courses(abbr_, name_) values('COMM 240', 'Health Communication');
insert into all_courses(abbr_, name_) values('BIOL 430', 'Histology');
insert into all_courses(abbr_, name_) values('HST 499', 'History Capstone: Undergraduate Dissertation');
insert into all_courses(abbr_, name_) values('HST 100', 'History of Kazakhstan');
insert into all_courses(abbr_, name_) values('HST 222', 'History of Medical Ethics');
insert into all_courses(abbr_, name_) values('HST 472/REL 472', 'History of Sufism in the Middle East and Central Asia');
insert into all_courses(abbr_, name_) values('WLL 251', 'Hong Kong Cinema');
insert into all_courses(abbr_, name_) values('BIOL 231', 'Human Anatomy and Physiology II');
insert into all_courses(abbr_, name_) values('ANT 261', 'Human Evolution: Bones, Stones and Genomes');
insert into all_courses(abbr_, name_) values('PHIL 431/PLS 420', 'Human Rights and Cultural Differences');
insert into all_courses(abbr_, name_) values('ROBT 310', 'Image Processing');
insert into all_courses(abbr_, name_) values('PLS 395', 'Independent Study');
insert into all_courses(abbr_, name_) values('HST 399', 'Independent Study');
insert into all_courses(abbr_, name_) values('CHEM 189c', 'Independent Study');
insert into all_courses(abbr_, name_) values('HST 220', 'India 1757-1947: Empire, Nationalism and Independence');
insert into all_courses(abbr_, name_) values('ROBT 308', 'Industrial Automation');
insert into all_courses(abbr_, name_) values('ECON 412', 'Industrial Organization');
insert into all_courses(abbr_, name_) values('CHEM 320', 'Instrumental Analysis with Labs');
insert into all_courses(abbr_, name_) values('FRE 202', 'Intermediate French II');
insert into all_courses(abbr_, name_) values('KAZ 111', 'Intermediate Kazakh I');
insert into all_courses(abbr_, name_) values('KAZ 114', 'Intermediate Kazakh II');
insert into all_courses(abbr_, name_) values('ECON 202', 'Intermediate Macroeconomics');
insert into all_courses(abbr_, name_) values('CHN 201', 'Intermediate Mandarin I');
insert into all_courses(abbr_, name_) values('ECON 201', 'Intermediate Microeconomics');
insert into all_courses(abbr_, name_) values('SPA 202', 'Intermediate Spanish II');
insert into all_courses(abbr_, name_) values('PLS 391', 'Intermediate Special Topics in Comparative Politics');
insert into all_courses(abbr_, name_) values('ECON 329', 'International Finance');
insert into all_courses(abbr_, name_) values('SOC 221', 'International Migration');
insert into all_courses(abbr_, name_) values('PLS 351', 'International Political Economy');
insert into all_courses(abbr_, name_) values('PLS 352', 'International Relations Theory');
insert into all_courses(abbr_, name_) values('PLS 457', 'International Security and Conflict');
insert into all_courses(abbr_, name_) values('ANT 160', 'Introduction to Biological Anthropology');
insert into all_courses(abbr_, name_) values('PLS 140', 'Introduction to Comparative Politics');
insert into all_courses(abbr_, name_) values('WLL 101', 'Introduction to Critical Issues in the Humanities and Social Sciences');
insert into all_courses(abbr_, name_) values('WLL 121', 'Introduction to Cultural Studies');
insert into all_courses(abbr_, name_) values('MATH 274', 'Introduction to Differential Equations');
insert into all_courses(abbr_, name_) values('MATH 407', 'Introduction to Graph Theory');
insert into all_courses(abbr_, name_) values('PLS 354', 'Introduction to International Law');
insert into all_courses(abbr_, name_) values('PLS 150', 'Introduction to International Relations');
insert into all_courses(abbr_, name_) values('WLL 131', 'Introduction to Linguistics');
insert into all_courses(abbr_, name_) values('WLL 110', 'Introduction to Literary Studies');
insert into all_courses(abbr_, name_) values('ECON 102', 'Introduction to Macroeconomics');
insert into all_courses(abbr_, name_) values('ECON 101', 'Introduction to Microeconomics');
insert into all_courses(abbr_, name_) values('MATH 351', 'Introduction to Numerical Methods with Applications');
insert into all_courses(abbr_, name_) values('PHIL 101', 'Introduction to Philosophy');
insert into all_courses(abbr_, name_) values('PLS 101', 'Introduction to Political Science');
insert into all_courses(abbr_, name_) values('PLS 120', 'Introduction to Political Theory');
insert into all_courses(abbr_, name_) values('SOC 218', 'Introduction to Social Policy');
insert into all_courses(abbr_, name_) values('ANT 101', 'Introduction to Sociocultural Anthropology');
insert into all_courses(abbr_, name_) values('SOC 101', 'Introduction to Sociology');
insert into all_courses(abbr_, name_) values('WLL 111', 'Introduction to Theatre');
insert into all_courses(abbr_, name_) values('WLL 155', 'Introduction to the Comic Book');
insert into all_courses(abbr_, name_) values('PHYS 202', 'Introductory Astronomy II');
insert into all_courses(abbr_, name_) values('MATH 361', 'Introductory Real Analysis I');
insert into all_courses(abbr_, name_) values('MATH 461', 'Introductory Real Analysis II');
insert into all_courses(abbr_, name_) values('ANT 313/PLS 332/REL 332', 'Islam and Politics in Eurasia');
insert into all_courses(abbr_, name_) values('BIOL 356', 'Junior Research');
insert into all_courses(abbr_, name_) values('PLS 422', 'Just War Theory');
insert into all_courses(abbr_, name_) values('KAZ 230', 'Kazakh Culture through Ethnography, Literature, and Film');
insert into all_courses(abbr_, name_) values('KAZ 225', 'Kazakh Diplomacy');
insert into all_courses(abbr_, name_) values('KAZ 366', 'Kazakh Language for Engineers');
insert into all_courses(abbr_, name_) values('KAZ 211', 'Kazakh Rhetoric');
insert into all_courses(abbr_, name_) values('KAZ 351', 'Kazakh Short Stories');
insert into all_courses(abbr_, name_) values('KAZ 213', 'Kazakh Terminology');
insert into all_courses(abbr_, name_) values('KAZ 313', 'Kazakh for Business');
insert into all_courses(abbr_, name_) values('KAZ 370', 'Kazakh for Career Development');
insert into all_courses(abbr_, name_) values('KAZ 364', 'Kazakh for Civil Service');
insert into all_courses(abbr_, name_) values('KAZ 226', 'Kazakh for Medical School');
insert into all_courses(abbr_, name_) values('ECON 328', 'Labor Economics');
insert into all_courses(abbr_, name_) values('KAZ 264', 'Language and ethnicity');
insert into all_courses(abbr_, name_) values('WLL 102 /PHIL 102', 'Language, Experience, Culture');
insert into all_courses(abbr_, name_) values('WLL 270', 'Languages of Eurasia');
insert into all_courses(abbr_, name_) values('PHYS 474', 'Lasers and Photonics');
insert into all_courses(abbr_, name_) values('MATH 273', 'Linear Algebra with Applications');
insert into all_courses(abbr_, name_) values('KAZ 357', 'Literature of Alash');
insert into all_courses(abbr_, name_) values('MATH 322', 'Mathematical Statistics');
insert into all_courses(abbr_, name_) values('ROBT 302', 'Mechanical Design II');
insert into all_courses(abbr_, name_) values('ROBT 206', 'Microcontrollers with Lab');
insert into all_courses(abbr_, name_) values('BIOL 110', 'Modern Biology I with Lab');
insert into all_courses(abbr_, name_) values('BIOL 120', 'Modern Biology II with Lab');
insert into all_courses(abbr_, name_) values('PLS 326', 'Modern Political Theory');
insert into all_courses(abbr_, name_) values('BIOL 220', 'Molecular Biology of Cell with Lab');
insert into all_courses(abbr_, name_) values('WLL 470', 'Multilingualism and Language Contact');
insert into all_courses(abbr_, name_) values('CHEM 490', 'Nanochemistry');
insert into all_courses(abbr_, name_) values('CHEM 413', 'Natural Product Chemistry');
insert into all_courses(abbr_, name_) values('ECON 322', 'Natural Resources and Environmental Economics');
insert into all_courses(abbr_, name_) values('PLS 472', 'Negotiation, Cooperation and Strategy');
insert into all_courses(abbr_, name_) values('BIOL 440', 'Neuroscience');
insert into all_courses(abbr_, name_) values('ANT 286', 'Nomads: Around the world and through time');
insert into all_courses(abbr_, name_) values('MATH 412', 'Nonlinear Optimization');
insert into all_courses(abbr_, name_) values('MATH 444', 'Nonparametric Methods');
insert into all_courses(abbr_, name_) values('KAZ 368', 'Onomastics: History and Function of Names');
insert into all_courses(abbr_, name_) values('CSCI 462', 'Open Source Software');
insert into all_courses(abbr_, name_) values('CSCI 232', 'Operating Systems');
insert into all_courses(abbr_, name_) values('PHYS 370', 'Optics with Laboratory');
insert into all_courses(abbr_, name_) values('CHEM 211', 'Organic Chemistry I');
insert into all_courses(abbr_, name_) values('CHEM 211L', 'Organic Chemistry I Lab');
insert into all_courses(abbr_, name_) values('CHEM 212', 'Organic Chemistry II');
insert into all_courses(abbr_, name_) values('CHEM 212L', 'Organic Chemistry II Lab');
insert into all_courses(abbr_, name_) values('CSCI 152', 'Performance and Data Structures');
insert into all_courses(abbr_, name_) values('PHIL 123', 'Philosophy of Science');
insert into all_courses(abbr_, name_) values('CHEM 332', 'Physical Chemistry II');
insert into all_courses(abbr_, name_) values('CHEM 332L', 'Physical Chemistry II Lab');
insert into all_courses(abbr_, name_) values('PHYS 495', 'Physics Colloquium');
insert into all_courses(abbr_, name_) values('PHYS 161', 'Physics I for Scientists and Engineers with Laboratory');
insert into all_courses(abbr_, name_) values('PHYS 162', 'Physics II for Scientists and Engineers with Laboratory');
insert into all_courses(abbr_, name_) values('PLS 210', 'Political Science Research Methods');
insert into all_courses(abbr_, name_) values('PLS 330', 'Politics and Governance of Eurasia');
insert into all_courses(abbr_, name_) values('PLS 431', 'Politics and Governance of the Russian Federation');
insert into all_courses(abbr_, name_) values('PLS 341', 'Politics of Development');
insert into all_courses(abbr_, name_) values('ANT 314/PLS 335', 'Politics of Identity in Eurasia');
insert into all_courses(abbr_, name_) values('MATH 321', 'Probability');
insert into all_courses(abbr_, name_) values('CSCI 353', 'Programming Paradigms');
insert into all_courses(abbr_, name_) values('CSCI 151', 'Programming for Scientists and Engineers');
insert into all_courses(abbr_, name_) values('SOC 214', 'Qualitative Methods');
insert into all_courses(abbr_, name_) values('PLS 211', 'Quantitative Methods in Political Science');
insert into all_courses(abbr_, name_) values('PHYS 451', 'Quantum Mechanics I');
insert into all_courses(abbr_, name_) values('ANT 400', 'Research Assistance in Anthropology');
insert into all_courses(abbr_, name_) values('ANT 403', 'Research Assistance in Anthropology');
insert into all_courses(abbr_, name_) values('ECON 300', 'Research Assistance in Economics');
insert into all_courses(abbr_, name_) values('SOC 403', 'Research Assistance in Sociology');
insert into all_courses(abbr_, name_) values('CHEM 380', 'Research Methods');
insert into all_courses(abbr_, name_) values('SHSS 150', 'Rhetoric and Composition');
insert into all_courses(abbr_, name_) values('ROBT 402', 'Robotic/Mechatronic System Design');
insert into all_courses(abbr_, name_) values('SHSS 300', 'SHSS Internship');
insert into all_courses(abbr_, name_) values('SHSS 301', 'SHSS Internship Second Experience');
insert into all_courses(abbr_, name_) values('COMM 350', 'Science, Health, and Social Influence');
insert into all_courses(abbr_, name_) values('SOC 220', 'Science, Technology, and Society');
insert into all_courses(abbr_, name_) values('CSCI 455', 'Scripting Languages');
insert into all_courses(abbr_, name_) values('CSCI 409', 'Senior Project II');
insert into all_courses(abbr_, name_) values('BIOL 491', 'Senior Thesis 2');
insert into all_courses(abbr_, name_) values('SOC 201', 'Social Science Research Methods');
insert into all_courses(abbr_, name_) values('ANT 399', 'Special Topics in Anthropology');
insert into all_courses(abbr_, name_) values('SOC 399', 'Special Topics in Sociology');
insert into all_courses(abbr_, name_) values('KAZ 314', 'Speech Culture in Business');
insert into all_courses(abbr_, name_) values('CHEM 092', 'Survey of Environmental Sciences for Non-Science Majors');
insert into all_courses(abbr_, name_) values('WLL 241', 'Survey of Folk Tales');
insert into all_courses(abbr_, name_) values('CSCI 245', 'System Analysis and Design');
insert into all_courses(abbr_, name_) values('ROBT 202', 'System Dynamics and Modeling');
insert into all_courses(abbr_, name_) values('KAZ 358', 'Technique of Translation');
insert into all_courses(abbr_, name_) values('PHIL 115', 'Technology and Life Decisions');
insert into all_courses(abbr_, name_) values('WLL 245', 'Terrible Perfection: Heroines of Classical Russian Literature');
insert into all_courses(abbr_, name_) values('ECON 326', 'The Economics of Financial Markets');
insert into all_courses(abbr_, name_) values('PLS 421', 'Theories of  Political Obligations');
insert into all_courses(abbr_, name_) values('PHYS 280', 'Thermodynamics and Statistical Physics');
insert into all_courses(abbr_, name_) values('PHIL 325', 'Truth, Lies, Media, and Propaganda');
insert into all_courses(abbr_, name_) values('PLS 338', 'U.S. Government and Politics');
insert into all_courses(abbr_, name_) values('HST 151', 'US History I (to 1877)');
insert into all_courses(abbr_, name_) values('CSCI 336', 'Ubiquity and Sensing');
insert into all_courses(abbr_, name_) values('KAZ 121', 'Upper-Intermediate Kazakh');
insert into all_courses(abbr_, name_) values('HST 122', 'World History II (from 1500)');
insert into all_courses(abbr_, name_) values('WLL 499', 'World Languages, Literature, and Culture Capstone');
insert into all_courses(abbr_, name_) values('WLL 211', 'World Literature II: from the 18th to the 20th century');
insert into all_courses(abbr_, name_) values('ANT 140', 'World Prehistory');
insert into all_courses(abbr_, name_) values('SHSS 331', 'Writing Fellows – Practicum in Composition & Collaboration II');
