DROP TABLE IF EXISTS feedback;
CREATE TABLE feedback (
    id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    userId int(10) UNSIGNED,
    courseId int(10),
    feedback text,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;